<?php

/**
 * PluginNoteAccentColorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNoteAccentColorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNoteAccentColorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNoteAccentColor');
    }
}