<?php

/**
 * PluginNoteTagRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNoteTagRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNoteTagRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNoteTagRelation');
    }
}