<?php

/**
 * PluginNoteTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNoteTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNoteTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNoteTag');
    }
}