<?php

/**
 * PluginNoteTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNoteTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNoteTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNoteType');
    }
}