<?php

/**
 * PluginNoteCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNoteCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNoteCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNoteCategory');
    }
}